### ISSUE TITLE
Develop collaborative workflow: direct push vs pull requests?

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/Covid19-Wastewater-Analysis#2]
Does it make sense for us to interact at the code level via GitHub pull requests?

Our current collaborative workflow is described [here]( https://swcarpentry.github.io/git-novice/08-collab/index.html#a-basic-collaborative-workflow)

[Here](https://sarahlrstevens.info/git-novice-mod/15-branching-PR/) is a lesson on pull requests that Sarah developed when she was a grad student.

Another version for contributing to carpentry lessons  [here](https://gcapes.github.io/swc-pr-tutorial/01-git-collaboration/index.html) 

To do @MarlinRLee @kyllan16693 :  briefly look over the workflows.
To do @SteveGoldstein : we can't fork the repo because we are owners. What's an appropriate modification?

**Comment by kyllan16693** [comment]
No longer needed
